version: '3.8'

services:

  master:
    build:
       context: ./master
       dockerfile: Dockerfile
    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:8000:8000"

  secondary-1:
    build:
       context: ./secondary
       dockerfile: Dockerfile
    environment:
      #delay on adding messages in seconds 
      - DELAY=0
    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:8001:8000"

  secondary-2:
    build:
       context: ./secondary
       dockerfile: Dockerfile
    environment:
      #delay on adding messages in seconds 
      - DELAY=0
    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:8002:8000"

